---
# tasks file for kubelet | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ kubelet_app }} {{ kubelet_version }} to {{ kubelet_bin_path }}
  get_url:
    url: "{{ kubelet_dl_url }}"
    dest: "{{ kubelet_bin_path }}/{{ kubelet_app }}"
    mode: "{{ kubelet_file_mode }}"

- name: "Debian/Ubuntu Family | Provision systemd service for {{ kubelet_app }} as {{ kubelet_systemd_template_out_dir }}/{{ kubelet_systemd_template_out_file }}"
  template:
    src: "{{ kubelet_systemd_template_in_file }}"
    dest: "{{ kubelet_systemd_template_out_dir }}/{{ kubelet_systemd_template_out_file }}"
    mode: '0644'
    owner: root
    group: root
  notify:
    - "Create {{ kubelet_systemd_dropin_dir }} for {{ kubelet_app }} systemd dropin directory."
    - "Provision systemd service dropin for {{ kubelet_app }}"
    - "Enable {{ kubelet_app }} systemd service"
    - "Set {{ kubelet_app }} systemd service state"
