---
# tasks file for kubelet | Debian/Ubuntu Family

- name: Debian/Ubuntu Family | Downloading archive for {{ kubelet_app }} {{ kubelet_version }} to {{ kubelet_bin_path }}
  get_url:
    url: "{{ kubelet_dl_url }}"
    dest: "{{ kubelet_bin_path }}/{{ kubelet_app }}"
    mode: "{{ kubelet_file_mode }}"
